apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-collector
  labels:
    app.kubernetes.io/name: analytics-collector
    app.kubernetes.io/part-of: huly
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics-collector
    spec:
      containers:
        - name: analytics-collector
          image: hardcoreeng/analytics-collector:latest
          ports:
            - name: http
              containerPort: 4017
          env:
            - name: PORT
              value: "4017"
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: SERVER_SECRET
            - name: SERVICE_ID
              value: "analytics-collector-service"
            - name: ACCOUNTS_URL
              valueFrom:
                configMapKeyRef:
                  name: huly-config
                  key: ACCOUNTS_URL_INTERNAL
            - name: STATS_URL
              valueFrom:
                configMapKeyRef:
                  name: huly-config
                  key: STATS_URL_INTERNAL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: huly-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
