packages:
  - foundations/utils/packages/platform-rig
  - foundations/utils/packages/ui-test
  - foundations/core/packages/account-client
  - foundations/core/packages/analytics
  - foundations/core/packages/analytics-service
  - foundations/core/packages/api-client
  - foundations/core/packages/collaborator-client
  - foundations/core/packages/core
  - foundations/core/packages/model
  - foundations/core/packages/platform
  - foundations/core/packages/query
  - foundations/core/packages/rank
  - foundations/core/packages/retry
  - foundations/core/packages/storage
  - foundations/core/packages/text
  - foundations/core/packages/text-core
  - foundations/core/packages/text-html
  - foundations/core/packages/text-markdown
  - foundations/core/packages/text-ydoc
  - foundations/core/packages/client
  - foundations/core/packages/client-resources
  - foundations/core/packages/rpc
  - foundations/core/packages/token
  - foundations/core/packages/hulylake-client
  - foundations/core/packages/storage-client
  - foundations/core/packages/measurements
  - foundations/core/packages/measurements-otlp
  - foundations/core/packages/postgres-base
  - foundations/communication/packages/types
  - foundations/communication/packages/sdk-types
  - foundations/communication/packages/shared
  - foundations/communication/packages/rest-client
  - foundations/communication/packages/cockroach
  - foundations/communication/packages/server
  - foundations/communication/packages/query
  - foundations/communication/packages/client-query
  - foundations/server/packages/client
  - foundations/server/packages/collaboration
  - foundations/server/packages/core
  - foundations/server/packages/datalake
  - foundations/server/packages/hulylake
  - foundations/server/packages/elastic
  - foundations/server/packages/kafka
  - foundations/server/packages/middleware
  - foundations/server/packages/minio
  - foundations/server/packages/mongo
  - foundations/server/packages/postgres
  - foundations/server/packages/s3
  - foundations/server/packages/server
  - foundations/server/packages/server-storage
  - packages/analytics-providers
  - packages/highlight
  - ws-tests/api-tests
  - packages/importer
  - packages/hls
  - packages/theme
  - packages/ui
  - plugins/uploader
  - plugins/uploader-assets
  - plugins/uploader-resources
  - models/uploader
  - plugins/media
  - plugins/media-resources
  - plugins/media-assets
  - models/media
  - plugins/recorder
  - plugins/recorder-resources
  - plugins/recorder-assets
  - models/recorder
  - plugins/presence
  - plugins/presence-resources
  - models/presence
  - packages/billing-client
  - packages/payment-client
  - dev/prod
  - server/indexer
  - server/server-pipeline
  - plugins/login
  - plugins/login-assets
  - plugins/login-resources
  - plugins/onboard
  - plugins/onboard-assets
  - plugins/onboard-resources
  - plugins/workbench
  - plugins/workbench-assets
  - plugins/workbench-resources
  - packages/presentation
  - models/presentation
  - plugins/view
  - plugins/view-assets
  - plugins/view-resources
  - models/core
  - models/all
  - models/view
  - plugins/contact
  - plugins/contact-assets
  - plugins/contact-resources
  - plugins/task
  - plugins/task-assets
  - plugins/task-resources
  - models/workbench
  - models/task
  - models/contact
  - plugins/text-editor
  - plugins/text-editor-assets
  - plugins/text-editor-resources
  - plugins/chunter
  - plugins/chunter-assets
  - plugins/chunter-resources
  - models/chunter
  - plugins/recruit
  - plugins/recruit-assets
  - plugins/recruit-resources
  - models/recruit
  - plugins/image-cropper
  - plugins/image-cropper-resources
  - models/server-core
  - server-plugins/attachment
  - models/server-attachment
  - server-plugins/attachment-resources
  - server-plugins/collaboration
  - models/server-collaboration
  - server-plugins/collaboration-resources
  - server-plugins/contact
  - models/server-contact
  - server-plugins/contact-resources
  - pods/front
  - pods/stats
  - pods/server
  - pods/external
  - server/front
  - server/account
  - server/account-service
  - server/workspace-service
  - server/collaborator
  - dev/tool
  - dev/import-tool
  - pods/account
  - pods/workspace
  - pods/collaborator
  - packages/panel
  - plugins/activity
  - plugins/activity-assets
  - plugins/activity-resources
  - models/activity
  - plugins/setting
  - plugins/setting-assets
  - plugins/setting-resources
  - models/setting
  - plugins/telegram
  - plugins/telegram-assets
  - plugins/telegram-resources
  - models/telegram
  - plugins/devmodel-resources
  - plugins/devmodel
  - plugins/attachment
  - plugins/attachment-assets
  - plugins/attachment-resources
  - models/attachment
  - plugins/lead
  - plugins/lead-assets
  - plugins/lead-resources
  - models/lead
  - models/gmail
  - plugins/gmail
  - plugins/gmail-assets
  - plugins/gmail-resources
  - plugins/global-profile
  - plugins/global-profile-assets
  - plugins/global-profile-resources
  - models/inventory
  - plugins/inventory
  - plugins/inventory-assets
  - plugins/inventory-resources
  - plugins/templates
  - plugins/templates-assets
  - plugins/templates-resources
  - models/templates
  - server-plugins/templates
  - models/server-templates
  - models/text-editor
  - server/tool
  - tests/sanity
  - ws-tests/sanity
  - qms-tests/sanity
  - packages/rekoni
  - models/notification
  - plugins/notification
  - plugins/notification-assets
  - plugins/notification-resources
  - server-plugins/notification
  - models/server-notification
  - server-plugins/notification-resources
  - plugins/tags
  - plugins/tags-assets
  - plugins/tags-resources
  - models/tags
  - server-plugins/chunter
  - models/server-chunter
  - server-plugins/chunter-resources
  - server-plugins/inventory
  - models/server-inventory
  - server-plugins/inventory-resources
  - server-plugins/lead
  - models/server-lead
  - server-plugins/lead-resources
  - server-plugins/recruit
  - models/server-recruit
  - server-plugins/recruit-resources
  - server-plugins/task
  - models/server-task
  - server-plugins/tracker
  - models/server-tracker
  - server-plugins/tracker-resources
  - server-plugins/task-resources
  - server-plugins/setting
  - models/server-setting
  - server-plugins/setting-resources
  - plugins/calendar
  - plugins/calendar-assets
  - plugins/calendar-resources
  - models/calendar
  - server-plugins/tags
  - models/server-tags
  - server-plugins/tags-resources
  - server-plugins/calendar
  - models/server-calendar
  - server-plugins/calendar-resources
  - server-plugins/gmail
  - models/server-gmail
  - server-plugins/gmail-resources
  - server-plugins/telegram
  - models/server-telegram
  - server-plugins/telegram-resources
  - plugins/tracker
  - plugins/tracker-assets
  - plugins/tracker-resources
  - models/tracker
  - plugins/board
  - plugins/board-assets
  - plugins/board-resources
  - models/board
  - packages/kanban
  - plugins/preference
  - plugins/preference-assets
  - models/preference
  - server-plugins/preference
  - server/backup
  - server/backup-service
  - pods/backup
  - pods/fulltext
  - pods/media
  - pods/preview
  - pods/link-preview
  - plugins/hr
  - plugins/hr-assets
  - plugins/hr-resources
  - models/hr
  - server-plugins/hr
  - models/server-hr
  - server-plugins/hr-resources
  - plugins/bitrix
  - plugins/bitrix-assets
  - plugins/bitrix-resources
  - models/bitrix
  - plugins/request
  - plugins/request-assets
  - plugins/request-resources
  - models/request
  - server-plugins/request
  - models/server-request
  - server-plugins/request-resources
  - server-plugins/view
  - models/server-view
  - server-plugins/view-resources
  - server-plugins/activity
  - models/server-activity
  - server-plugins/activity-resources
  - models/support
  - plugins/support
  - plugins/support-assets
  - plugins/support-resources
  - plugins/guest
  - plugins/guest-assets
  - plugins/guest-resources
  - models/guest
  - server-plugins/guest
  - models/server-guest
  - server-plugins/guest-resources
  - pods/authProviders
  - plugins/time
  - plugins/time-assets
  - plugins/time-resources
  - models/time
  - server-plugins/time
  - server-plugins/time-resources
  - models/server-time
  - plugins/document
  - plugins/document-assets
  - plugins/document-resources
  - models/document
  - server-plugins/document
  - server-plugins/document-resources
  - models/server-document
  - plugins/love
  - plugins/love-assets
  - plugins/love-resources
  - models/love
  - server-plugins/love
  - server-plugins/love-resources
  - models/server-love
  - plugins/drive
  - plugins/drive-assets
  - plugins/drive-resources
  - models/drive
  - server-plugins/drive
  - models/server-drive
  - server-plugins/drive-resources
  - plugins/controlled-documents
  - plugins/controlled-documents-assets
  - plugins/controlled-documents-resources
  - plugins/converter
  - plugins/converter-resources
  - models/converter
  - models/controlled-documents
  - server-plugins/controlled-documents
  - server-plugins/controlled-documents-resources
  - models/server-controlled-documents
  - plugins/print
  - plugins/print-assets
  - plugins/print-resources
  - models/print
  - models/export
  - plugins/export
  - plugins/export-assets
  - plugins/export-resources
  - plugins/sign
  - plugins/products
  - plugins/products-assets
  - plugins/products-resources
  - models/products
  - models/server-products
  - plugins/questions
  - plugins/questions-assets
  - plugins/questions-resources
  - models/questions
  - plugins/training
  - plugins/training-assets
  - plugins/training-resources
  - server-plugins/training
  - server-plugins/training-resources
  - models/training
  - models/server-training
  - desktop
  - desktop-package
  - qms-desktop-package
  - plugins/diffview
  - plugins/diffview-assets
  - plugins/diffview-resources
  - services/github/github
  - services/github/github-assets
  - services/github/github-resources
  - services/github/model-github
  - services/github/pod-github
  - services/github/server-github
  - services/github/server-github-resources
  - services/github/server-github-model
  - plugins/desktop-preferences
  - plugins/desktop-preferences-assets
  - plugins/desktop-preferences-resources
  - models/desktop-preferences
  - plugins/desktop-downloads
  - plugins/desktop-downloads-assets
  - plugins/desktop-downloads-resources
  - models/desktop-downloads
  - services/notification/pod-notification
  - services/telegram/pod-telegram
  - services/gmail/pod-gmail
  - services/calendar/pod-calendar
  - services/calendar/pod-calendar-mailer
  - dev/doc-import-tool
  - services/datalake/pod-datalake
  - services/billing/pod-billing
  - services/payment/pod-payment
  - services/love
  - services/print/pod-print
  - services/export/pod-export
  - services/sign/pod-sign
  - services/rekoni
  - services/analytics-collector/pod-analytics-collector
  - plugins/analytics-collector
  - plugins/analytics-collector-assets
  - plugins/analytics-collector-resources
  - models/analytics-collector
  - server-plugins/analytics-collector
  - server-plugins/analytics-collector-resources
  - services/ai-bot/pod-ai-bot
  - plugins/ai-bot
  - plugins/ai-bot-resources
  - models/ai-bot
  - models/server-ai-bot
  - server-plugins/ai-bot
  - server-plugins/ai-bot-resources
  - services/telegram-bot/pod-telegram-bot
  - plugins/openai
  - common/scripts
  - models/test-management
  - plugins/test-management
  - plugins/test-management-resources
  - plugins/test-management-assets
  - plugins/survey
  - models/survey
  - plugins/survey-assets
  - plugins/survey-resources
  - plugins/card
  - models/card
  - plugins/card-assets
  - plugins/card-resources
  - server-plugins/card
  - server-plugins/card-resources
  - models/server-card
  - plugins/mail
  - models/mail
  - plugins/mail-assets
  - services/mail/pod-mail
  - plugins/chat
  - plugins/chat-assets
  - plugins/chat-resources
  - models/chat
  - plugins/process
  - plugins/process-assets
  - plugins/process-resources
  - models/process
  - server-plugins/process
  - models/server-process
  - server-plugins/process-resources
  - plugins/inbox
  - plugins/inbox-assets
  - plugins/inbox-resources
  - models/inbox
  - services/mail/pod-mail-worker
  - plugins/achievement
  - plugins/achievement-assets
  - plugins/achievement-resources
  - models/achievement
  - packages/kvs-client
  - packages/hulypulse-client
  - plugins/communication
  - plugins/communication-assets
  - plugins/communication-resources
  - models/communication
  - services/mail/mail-common
  - plugins/emoji
  - plugins/emoji-assets
  - plugins/emoji-resources
  - models/emoji
  - services/backup/backup-api-pod
  - plugins/billing
  - plugins/billing-assets
  - plugins/billing-resources
  - models/billing
  - services/process
  - packages/integration-client
  - models/huly-mail
  - plugins/huly-mail
  - plugins/huly-mail-assets
  - plugins/huly-mail-resources
  - models/ai-assistant
  - plugins/ai-assistant
  - plugins/ai-assistant-assets
  - plugins/ai-assistant-resources
  - services/worker
  - services/translate
  - plugins/rating
  - plugins/rating-assets
  - plugins/rating-resources
  - server-plugins/rating
  - models/rating
  - services/rating
