apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-data
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: huly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
