apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-data
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: huly
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 5Gi
